version: '2'

services:
  nginx:
    image: docker.io/bitnami/nginx:1.21
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - ./conf:/opt/bitnami/nginx/conf
      - ./ssl:/opt/bitnami/nginx/ssl
    restart: always