version: '3.3'

services:
  app1:
    build: ..
    environment:
      - 'ASPNETCORE_ENVIRONMENT=Staging'
      - 'Serilog__MinimumLevel__Override__Notifon=Verbose'
    env_file: secret.env
    extra_hosts:
      - "notify-contest.ddns.net:192.168.31.200"
  app2:
    build: ..
    environment:
      - 'ASPNETCORE_ENVIRONMENT=Staging'
      - 'Serilog__MinimumLevel__Override__Notifon=Verbose'
    env_file: secret.env
    extra_hosts:
      - "notify-contest.ddns.net:192.168.31.200"
  app3:
    build: ..
    environment:
      - 'ASPNETCORE_ENVIRONMENT=Staging'
      - 'Serilog__MinimumLevel__Override__Notifon=Verbose'
    env_file: secret.env
    extra_hosts:
      - "notify-contest.ddns.net:192.168.31.200"
  redis:
    ports:
      - '6379:6379'
  postgresql:
    ports:
      - '5432:5432'
  rabbitmq:
    ports:
      - '5672:5672'
      - '15672:15672'
