version: '3.3'

services:
  app:
    build: ..
    environment:
      - 'ASPNETCORE_ENVIRONMENT=Staging'
    env_file: .env
    extra_hosts:
      - "notify-contest.ddns.net:192.168.31.200"
  redis:
    ports:
      - '6379:6379'
  postgresql:
    ports:
      - '5432:5432'
  rabbitmq:
    ports:
      - '5672:5672'
      - '15672:15672'
